name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'master'
  schedule:
    - cron: '1 9 * * 0'

jobs:
  test_unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - symfony: '4.4.*'
            php: '7.4'
          - symfony: '4.4.*'
            php: '8.0'
          - symfony: '4.4.*'
            php: '8.1'
          - symfony: '5.4.*'
            php: '7.4'
          - symfony: '5.4.*'
            php: '8.0'
          - symfony: '5.4.*'
            php: '8.1'
          - symfony: '6.0.*'
            php: '8.0'
          - symfony: '6.0.*'
            php: '8.1'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: prepare test environment
        run: |
          Tests/Functional/Scripts/downloadComposer.sh
          composer config extra.symfony.require "${{ matrix.symfony }}"
          composer config extra.symfony.allow-contrib true
          composer config --no-plugins allow-plugins.symfony/flex true
          # adds flex, suppress composer.lock
          composer require symfony/flex --no-update
          # create a lock file
          composer install
          # updates to SYMFONY_VERSION, but runs recipes
          composer update symfony/*
          # reset tracked files
          git reset --hard
          # clean up recipe generated files and folders
          git clean -df
      - name: execute unit tests
        run: |
          composer config --no-plugins allow-plugins.symfony/flex true
          composer run-script quality
      - name: upload coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php vendor/bin/php-coveralls --exclude-no-stmt --coverage_clover=build/logs/clover.xml -v

  test_functional:
    name: Functional Tests
    needs:
      - test_unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - symfony: '4.4.*'
            php: '7.4'
          - symfony: '4.4.*'
            php: '8.0'
          - symfony: '4.4.*'
            php: '8.1'
          - symfony: '5.4.*'
            php: '7.4'
          - symfony: '5.4.*'
            php: '8.0'
          - symfony: '5.4.*'
            php: '8.1'
          - symfony: '6.0.*'
            php: '8.0'
          - symfony: '6.0.*'
            php: '8.1'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: prepare test environment
        run: |
          Tests/Functional/Scripts/downloadComposer.sh
          composer config extra.symfony.require "${{ matrix.symfony }}"
          composer config extra.symfony.allow-contrib true
          composer config --no-plugins allow-plugins.symfony/flex true
          # adds flex, suppress composer.lock
          composer require symfony/flex --no-update
          # create a lock file
          composer install
          # updates to SYMFONY_VERSION, but runs recipes
          composer update symfony/*
          # reset tracked files
          git reset --hard
          # clean up recipe generated files and folders
          git clean -df
      - name: install symfony cli
        run: |
          wget https://get.symfony.com/cli/installer -O symfony-installer.sh
          chmod a+x symfony-installer.sh
          sudo ./symfony-installer.sh --install-dir /usr/local/bin
      - name: execute functional tests
        env:
          SYMFONY_VERSION: ${{ matrix.symfony }}
          WITHOUT_JAEGER: true
        run: |
          composer config --no-plugins allow-plugins.symfony/flex true
          composer run-script phpunit-functional
      - name: show running containers
        run: docker ps
