name: test

on:
  push:
    branches:
      - '*'

jobs:
  test_unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: '7.1'
            symfony: '3.4.*'
          - php: '7.4'
            symfony: '3.4.*'
          - php: '7.2'
            symfony: '4.4.*'
          - php: '7.4'
            symfony: '4.4.*'
          - php: '7.2'
            symfony: '5.1.*'
          - php: '7.4'
            symfony: '5.1.*'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup php
        uses: nanasess/setup-php@v3
        with:
          php-version: ${{ matrix.php }}
      - name: prepare test environment
        run: |
          .github/workflows/download-composer.sh
          composer config extra.symfony.require "${{ matrix.symfony }}"
          composer config extra.symfony.allow-contrib true
          # adds flex, suppress composer.lock
          composer require symfony/flex --no-update
          # create a lock file
          composer install
          # updates to SYMFONY_VERSION, but runs recipes
          composer update symfony/*
          # reset tracked files
          git reset --hard
          # clean up recipe generated files and folders
          git clean -df
      - name: execute unit tests
        run: composer run-script quality

  test_functional:
    name: Functional Tests
    needs:
      - test_unit
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: |
          echo "functional tests"
